# Generated by Django 4.0.2 on 2022-04-20 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_tagarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagarticles',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Тема статьи'),
            preserve_default=False,
        ),
    ]
